//! Runtime data files (port of `freight_fate/data/data_resources.py`).
//!
//! Every runtime loader of a loose data file under `freight_fate/data`
//! must go through [`read_data_text`]; reading siblings of the source tree
//! directly works in a source checkout and silently (or loudly) breaks in a
//! packaged build. The Python original also had a baked-module branch
//! (`_baked_data`, generated by `tools/bake_data.py`) for frozen builds; the
//! Rust release ships the JSON tree on disk next to the executable, so the
//! only question here is WHERE the tree is, answered once by [`data_root`].

use std::path::{Path, PathBuf};

use once_cell::sync::OnceCell;

/// Environment variable that pins the data tree for a run (tests, tooling,
/// a portable install that keeps its data elsewhere).
pub const DATA_ROOT_ENV: &str = "FREIGHT_FATE_DATA_ROOT";

/// Every file `tools/bake_data.py` compiles into frozen builds. Kept here,
/// next to the reader, so a new runtime data file only needs one
/// registration to reach both source and packaged players.
pub const BAKED_DATA_FILES: &[&str] = &[
    "buffs.json",
    "city_services.json",
    "facility_approaches.json",
    "facility_endpoints.json",
    "local_approaches.json",
    "local_geometry.json",
    "radio_catalog.json",
    "radio_imported.json",
    "world_data/us/gameplay/curves.jsonl",
    "world_data/us/gameplay/curve_artifacts.jsonl",
];

static DATA_ROOT: OnceCell<PathBuf> = OnceCell::new();

/// Walk up from `start` looking for `src/freight_fate/data`.
fn find_source_tree(start: &Path) -> Option<PathBuf> {
    let mut cursor = Some(start);
    while let Some(dir) = cursor {
        let candidate = dir.join("src").join("freight_fate").join("data");
        if candidate.is_dir() {
            return Some(candidate);
        }
        cursor = dir.parent();
    }
    None
}

fn resolve_data_root() -> PathBuf {
    if let Some(root) = std::env::var_os(DATA_ROOT_ENV) {
        let root = PathBuf::from(root);
        if !root.as_os_str().is_empty() {
            return root;
        }
    }
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(Path::to_path_buf));
    if let Some(dir) = &exe_dir {
        // A packaged build: `freight_fate/data` beside the executable.
        let packaged = dir.join("freight_fate").join("data");
        if packaged.is_dir() {
            return packaged;
        }
        // A source checkout run from `target/...`.
        if let Some(found) = find_source_tree(dir) {
            return found;
        }
    }
    // The crate's own manifest directory: `crates/ff-core` -> repo root.
    if let Some(found) = find_source_tree(Path::new(env!("CARGO_MANIFEST_DIR"))) {
        return found;
    }
    // Nothing found; callers see `None` from `read_data_text` and degrade.
    exe_dir
        .map(|dir| dir.join("freight_fate").join("data"))
        .unwrap_or_else(|| PathBuf::from("freight_fate/data"))
}

/// The directory that stands in for the Python package's `data/` folder.
///
/// Resolved once per process: `FREIGHT_FATE_DATA_ROOT` if set, else
/// `<exe dir>/freight_fate/data` if it exists (a packaged build), else the
/// source tree `src/freight_fate/data` found by walking up from the
/// executable or from this crate's manifest directory.
pub fn data_root() -> &'static Path {
    DATA_ROOT.get_or_init(resolve_data_root)
}

/// Absolute path of a runtime data file under [`data_root`].
pub fn data_path(relative: &str) -> PathBuf {
    data_root().join(relative)
}

/// The text of a runtime data file, or `None` when it does not exist.
/// Callers that cannot degrade gracefully raise on `None` themselves.
pub fn read_data_text(relative: &str) -> Option<String> {
    read_text_at(&data_path(relative))
}

/// Read a UTF-8 text file, `None` when it does not exist (or cannot be read).
pub fn read_text_at(path: &Path) -> Option<String> {
    if !path.exists() {
        return None;
    }
    std::fs::read_to_string(path).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn data_root_resolves_to_the_source_tree_in_a_checkout() {
        let root = data_root();
        assert!(
            root.join("world_data").join("index.json").is_file(),
            "{root:?}"
        );
    }

    #[test]
    fn read_data_text_returns_none_for_a_missing_file() {
        assert!(read_data_text("definitely-not-a-real-file.json").is_none());
        assert!(read_data_text("buffs.json").is_some());
    }
}
