//! Bit-exact port of CPython 3.12's `random.Random` (MT19937).
//!
//! The Python game seeds `random.Random` from trip seeds, xor'd ints,
//! `"parking:{seed}:{mi}"` style strings and sha256-derived 64-bit ints, and
//! 119 transcript tests pin spoken lines that fall out of those draws. So
//! this is not "a Mersenne Twister": every public function below mirrors a
//! specific CPython routine, named in its doc comment, and the fixture tests
//! in `pyrandom/fixture_tests.rs` hold it to CPython's own output
//! (`tests/pyrandom_fixtures.json`, generated by
//! `tests/gen_pyrandom_fixtures.py` with the repo venv's Python 3.12).
//!
//! Sources mirrored (CPython 3.12):
//!
//! - `Modules/_randommodule.c`: `genrand_uint32`, `init_genrand`,
//!   `init_by_array`, `random_seed`, `random_random`, `random_getrandbits`,
//!   `random_getstate`, `random_setstate`.
//! - `Lib/random.py`: `Random.seed` (version-2 str seeding), `_randbelow`,
//!   `randrange`, `randint`, `choice`, `choices`, `sample`, `shuffle`,
//!   `uniform`, `triangular`, `expovariate`, `gauss`, `normalvariate`,
//!   `getstate`/`setstate` (the `gauss_next` slot).
//!
//! Not ported (the game never calls them): `Random(float)` / `Random(bytes)`
//! seeding, `randbytes`, the `counts=` form of `sample`, `betavariate`,
//! `gammavariate`, `lognormvariate`, `vonmisesvariate`, `paretovariate`,
//! `weibullvariate`, `binomialvariate`, and version-1 str seeding.
//!
//! Python raises `ValueError`/`IndexError` on empty ranges and sequences;
//! the game never reaches those, so the Rust side panics with the same
//! message rather than threading a `Result` through every draw.

use std::collections::HashSet;
use std::hash::{BuildHasher, Hasher};

use sha2::{Digest, Sha256, Sha512};

#[cfg(test)]
mod fixture_tests;

/// MT19937 state length (`N` in `_randommodule.c`).
pub const N: usize = 624;
/// MT19937 middle word (`M` in `_randommodule.c`).
const M: usize = 397;
const MATRIX_A: u32 = 0x9908_b0df;
const UPPER_MASK: u32 = 0x8000_0000;
const LOWER_MASK: u32 = 0x7fff_ffff;

/// `NV_MAGICCONST = 4 * exp(-0.5) / sqrt(2.0)` from `Lib/random.py`,
/// computed the same way CPython does at import.
fn nv_magicconst() -> f64 {
    4.0 * (-0.5f64).exp() / 2.0f64.sqrt()
}

/// Snapshot of a [`PyRandom`], the Rust shape of Python's
/// `Random.getstate()` tuple `(VERSION, (mt[0..624], index), gauss_next)`.
///
/// `sim/weather.py` clones one generator from another with
/// `rng.setstate(self._rng.getstate())`; that is [`PyRandom::getstate`] into
/// [`PyRandom::setstate`] here, or simply `.clone()` on the generator.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PyRandomState {
    /// The 624 MT words (`state[]` in C).
    pub mt: [u32; N],
    /// Position of the next word to temper, `0..=624` (`index` in C; 624
    /// means "twist before the next draw").
    pub index: usize,
    /// `Random.gauss_next`: the spare normal deviate `gauss()` keeps for its
    /// next call, as raw `f64` bits so the state stays `Eq` (`None` is
    /// Python's `None`).
    pub gauss_next: Option<u64>,
}

/// A CPython-3.12-compatible `random.Random` instance.
///
/// Construct it exactly the way the Python site does:
/// [`new_from_i64`](PyRandom::new_from_i64) /
/// [`new_from_u64`](PyRandom::new_from_u64) /
/// [`new_from_i128`](PyRandom::new_from_i128) for `Random(int)`,
/// [`new_from_str`](PyRandom::new_from_str) for `Random("text")`,
/// [`new_from_sha256_prefix16`](PyRandom::new_from_sha256_prefix16) for
/// `Random(int(sha256(key).hexdigest()[:16], 16))`, and
/// [`new_unseeded`](PyRandom::new_unseeded) for `Random()`.
#[derive(Clone, Debug)]
pub struct PyRandom {
    mt: [u32; N],
    index: usize,
    gauss_next: Option<f64>,
}

impl PartialEq for PyRandom {
    fn eq(&self, other: &Self) -> bool {
        self.getstate() == other.getstate()
    }
}
impl Eq for PyRandom {}

// ---------------------------------------------------------------------------
// Seeding
// ---------------------------------------------------------------------------

/// `init_by_array(self, init_key, key_length)` from `_randommodule.c`,
/// returned as a fresh generator. `key` is used verbatim (no trimming of
/// high zero words). An empty key is never reachable from Python; it is
/// treated as the single word `[0]`.
pub fn init_by_array(key: &[u32]) -> PyRandom {
    let mut r = PyRandom {
        mt: [0; N],
        index: N,
        gauss_next: None,
    };
    r.seed_by_array(key);
    r
}

/// The `init_by_array` key CPython derives from an integer seed
/// (`random_seed` in `_randommodule.c`): `abs(n)` split into 32-bit words,
/// least significant first, `max(1, ceil(bit_length / 32))` words long.
///
/// `le_bytes` is the magnitude as little-endian bytes (any length).
pub fn int_words_from_le_bytes(le_bytes: &[u8]) -> Vec<u32> {
    let mut words: Vec<u32> = le_bytes
        .chunks(4)
        .map(|c| {
            let mut w = [0u8; 4];
            w[..c.len()].copy_from_slice(c);
            u32::from_le_bytes(w)
        })
        .collect();
    while words.len() > 1 && words[words.len() - 1] == 0 {
        words.pop();
    }
    if words.is_empty() {
        words.push(0);
    }
    words
}

/// The integer CPython's `Random.seed(str, version=2)` feeds to
/// `random_seed`, as `init_by_array` words:
/// `int.from_bytes(s.encode() + sha512(s.encode()).digest(), 'big')`
/// split into little-endian 32-bit words (see [`int_words_from_le_bytes`]).
pub fn seed_from_str_to_words(s: &str) -> Vec<u32> {
    let bytes = s.as_bytes();
    let mut big_endian = Vec::with_capacity(bytes.len() + 64);
    big_endian.extend_from_slice(bytes);
    big_endian.extend_from_slice(&Sha512::digest(bytes));
    big_endian.reverse();
    int_words_from_le_bytes(&big_endian)
}

/// `int(hashlib.sha256(key.encode()).hexdigest()[:16], 16)`: the first 16 hex
/// characters of the digest, i.e. its first eight bytes read big-endian.
/// This is how `sim/traffic_manager.py` derives its per-route seeds.
pub fn sha256_prefix16(key: &str) -> u64 {
    let digest = Sha256::digest(key.as_bytes());
    let mut eight = [0u8; 8];
    eight.copy_from_slice(&digest[..8]);
    u64::from_be_bytes(eight)
}

impl PyRandom {
    /// `random.Random(n)` for an `int` that fits `i64` (negative seeds use
    /// `abs(n)`, as `random_seed` does).
    pub fn new_from_i64(seed: i64) -> Self {
        Self::new_from_big_uint_le(&seed.unsigned_abs().to_le_bytes())
    }

    /// `random.Random(n)` for a non-negative `int` that fits `u64`.
    pub fn new_from_u64(seed: u64) -> Self {
        Self::new_from_big_uint_le(&seed.to_le_bytes())
    }

    /// `random.Random(n)` for an `int` that fits `i128` — enough for every
    /// `(trip_seed << 16) ^ x` and `seed * 1_000_003 + day` the game forms.
    pub fn new_from_i128(seed: i128) -> Self {
        Self::new_from_big_uint_le(&seed.unsigned_abs().to_le_bytes())
    }

    /// `random.Random(n)` for an arbitrary non-negative `int` given as its
    /// magnitude in little-endian bytes (what `n.to_bytes(k, 'little')`
    /// yields). Negative seeds: pass `abs(n)`.
    pub fn new_from_big_uint_le(le_bytes: &[u8]) -> Self {
        init_by_array(&int_words_from_le_bytes(le_bytes))
    }

    /// `random.Random(n)` for an `int` already split into little-endian
    /// 32-bit words. High zero words are trimmed first (CPython sizes the
    /// key from `bit_length`), so `[5, 0]` seeds the same as `[5]`.
    pub fn new_from_int_words(words: &[u32]) -> Self {
        let mut end = words.len();
        while end > 1 && words[end - 1] == 0 {
            end -= 1;
        }
        if end == 0 {
            init_by_array(&[0])
        } else {
            init_by_array(&words[..end])
        }
    }

    /// `random.Random("text")`: `Random.seed(a, version=2)` for a `str`,
    /// which hashes the UTF-8 bytes with sha512 (see
    /// [`seed_from_str_to_words`]) and then takes the `int` path.
    pub fn new_from_str(s: &str) -> Self {
        init_by_array(&seed_from_str_to_words(s))
    }

    /// `random.Random(int(hashlib.sha256(key.encode()).hexdigest()[:16], 16))`
    /// (see [`sha256_prefix16`]).
    pub fn new_from_sha256_prefix16(key: &str) -> Self {
        Self::new_from_u64(sha256_prefix16(key))
    }

    /// `random.Random()` — seeded from entropy, so never reproducible.
    ///
    /// CPython pulls 624 words from `os.urandom`; this mixes the std
    /// `RandomState` hasher (itself OS-seeded) with the clock. It only needs
    /// to be unpredictable, which is all `audio.py`'s wobble and
    /// `sim/weather.py`'s scratch generator ask of it.
    pub fn new_unseeded() -> Self {
        let mut key = Vec::with_capacity(N);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        for i in 0..(N / 2) as u64 {
            let mut h = std::collections::hash_map::RandomState::new().build_hasher();
            h.write_u64(i);
            h.write_u128(nanos);
            let v = h.finish();
            key.push(v as u32);
            key.push((v >> 32) as u32);
        }
        init_by_array(&key)
    }

    /// `Random.seed(n)` on an existing instance with an `i64` seed.
    pub fn seed_i64(&mut self, seed: i64) {
        *self = Self::new_from_i64(seed);
    }

    /// `Random.seed("text")` on an existing instance.
    pub fn seed_str(&mut self, s: &str) {
        *self = Self::new_from_str(s);
    }

    /// `init_genrand(self, s)` from `_randommodule.c`.
    fn init_genrand(&mut self, s: u32) {
        let mt = &mut self.mt;
        mt[0] = s;
        for mti in 1..N {
            mt[mti] = 1_812_433_253u32
                .wrapping_mul(mt[mti - 1] ^ (mt[mti - 1] >> 30))
                .wrapping_add(mti as u32);
        }
        self.index = N;
    }

    /// `init_by_array(self, init_key, key_length)` from `_randommodule.c`,
    /// in place. Resets `gauss_next`, as `Random.seed` does.
    fn seed_by_array(&mut self, key: &[u32]) {
        let key: &[u32] = if key.is_empty() { &[0] } else { key };
        self.init_genrand(19_650_218);
        let mt = &mut self.mt;
        let key_length = key.len();
        let mut i = 1usize;
        let mut j = 0usize;
        let mut k = if N > key_length { N } else { key_length };
        while k > 0 {
            mt[i] = (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)).wrapping_mul(1_664_525)))
                .wrapping_add(key[j])
                .wrapping_add(j as u32);
            i += 1;
            j += 1;
            if i >= N {
                mt[0] = mt[N - 1];
                i = 1;
            }
            if j >= key_length {
                j = 0;
            }
            k -= 1;
        }
        k = N - 1;
        while k > 0 {
            mt[i] = (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)).wrapping_mul(1_566_083_941)))
                .wrapping_sub(i as u32);
            i += 1;
            if i >= N {
                mt[0] = mt[N - 1];
                i = 1;
            }
            k -= 1;
        }
        mt[0] = 0x8000_0000;
        self.index = N;
        self.gauss_next = None;
    }

    // -----------------------------------------------------------------------
    // Core generator
    // -----------------------------------------------------------------------

    /// `genrand_uint32(self)` from `_randommodule.c`: one tempered 32-bit
    /// word, twisting the whole state first when it is exhausted.
    pub fn genrand_u32(&mut self) -> u32 {
        if self.index >= N {
            self.twist();
        }
        let mut y = self.mt[self.index];
        self.index += 1;
        y ^= y >> 11;
        y ^= (y << 7) & 0x9d2c_5680;
        y ^= (y << 15) & 0xefc6_0000;
        y ^= y >> 18;
        y
    }

    fn twist(&mut self) {
        let mt = &mut self.mt;
        let mag01 = |y: u32| if y & 1 == 0 { 0 } else { MATRIX_A };
        let mut kk = 0;
        while kk < N - M {
            let y = (mt[kk] & UPPER_MASK) | (mt[kk + 1] & LOWER_MASK);
            mt[kk] = mt[kk + M] ^ (y >> 1) ^ mag01(y);
            kk += 1;
        }
        while kk < N - 1 {
            let y = (mt[kk] & UPPER_MASK) | (mt[kk + 1] & LOWER_MASK);
            mt[kk] = mt[kk + M - N] ^ (y >> 1) ^ mag01(y);
            kk += 1;
        }
        let y = (mt[N - 1] & UPPER_MASK) | (mt[0] & LOWER_MASK);
        mt[N - 1] = mt[M - 1] ^ (y >> 1) ^ mag01(y);
        self.index = 0;
    }

    /// `random_random(self)` (`genrand_res53`): a float in `[0.0, 1.0)` with
    /// 53 random bits, `(a*67108864.0+b)*(1.0/9007199254740992.0)`.
    pub fn random(&mut self) -> f64 {
        let a = self.genrand_u32() >> 5;
        let b = self.genrand_u32() >> 6;
        (f64::from(a) * 67_108_864.0 + f64::from(b)) * (1.0 / 9_007_199_254_740_992.0)
    }

    /// `random_getrandbits(self, k)` from `_randommodule.c`, returned as the
    /// little-endian 32-bit words CPython hands to `_PyLong_FromByteArray`.
    /// Words are filled least significant first; when `k` is not a multiple
    /// of 32 the LAST word is the one shifted down. `k == 0` yields `[0]`
    /// without drawing.
    pub fn getrandbits_words(&mut self, k: u64) -> Vec<u32> {
        if k == 0 {
            return vec![0];
        }
        if k <= 32 {
            return vec![self.genrand_u32() >> (32 - k as u32)];
        }
        let words = ((k - 1) / 32 + 1) as usize;
        let mut out = Vec::with_capacity(words);
        let mut k = k;
        for _ in 0..words {
            let mut r = self.genrand_u32();
            if k < 32 {
                r >>= 32 - k as u32;
            }
            out.push(r);
            k = k.saturating_sub(32);
        }
        out
    }

    /// `Random.getrandbits(k)` for `k <= 128`, as an integer.
    ///
    /// # Panics
    /// If `k > 128`; use [`getrandbits_words`](Self::getrandbits_words).
    pub fn getrandbits(&mut self, k: u32) -> u128 {
        assert!(k <= 128, "getrandbits(k) as u128 needs k <= 128, got {k}");
        let words = self.getrandbits_words(u64::from(k));
        let mut v: u128 = 0;
        for (i, w) in words.iter().enumerate() {
            v |= u128::from(*w) << (32 * i);
        }
        v
    }

    /// `Random.getrandbits(k)` for `k <= 64`, as a `u64`.
    ///
    /// # Panics
    /// If `k > 64`.
    pub fn getrandbits_u64(&mut self, k: u32) -> u64 {
        assert!(k <= 64, "getrandbits_u64(k) needs k <= 64, got {k}");
        self.getrandbits(k) as u64
    }

    // -----------------------------------------------------------------------
    // Integer helpers (Lib/random.py)
    // -----------------------------------------------------------------------

    /// `Random._randbelow_with_getrandbits(n)`: `k = n.bit_length()`, draw
    /// `getrandbits(k)` until it is `< n`. Returns `0 <= r < n`.
    ///
    /// # Panics
    /// If `n == 0`. No Python caller passes 0 (`randrange`/`choice` raise
    /// first), so nothing depends on what CPython would do there.
    pub fn randbelow(&mut self, n: u64) -> u64 {
        assert!(n > 0, "randbelow(0)");
        let k = 64 - n.leading_zeros();
        let mut r = self.getrandbits_u64(k);
        while r >= n {
            r = self.getrandbits_u64(k);
        }
        r
    }

    /// `_randbelow` for `n` up to 128 bits.
    pub fn randbelow_u128(&mut self, n: u128) -> u128 {
        assert!(n > 0, "randbelow(0)");
        let k = 128 - n.leading_zeros();
        let mut r = self.getrandbits(k);
        while r >= n {
            r = self.getrandbits(k);
        }
        r
    }

    /// `Random.randrange(stop)`: `_randbelow(stop)`.
    ///
    /// # Panics
    /// If `stop <= 0` (Python: `ValueError("empty range for randrange()")`).
    pub fn randrange(&mut self, stop: i64) -> i64 {
        assert!(stop > 0, "empty range for randrange({stop})");
        self.randbelow(stop as u64) as i64
    }

    /// `Random.randrange(start, stop)`: `start + _randbelow(stop - start)`.
    ///
    /// # Panics
    /// If `stop <= start` (Python: `ValueError`).
    pub fn randrange2(&mut self, start: i64, stop: i64) -> i64 {
        let width = i128::from(stop) - i128::from(start);
        assert!(width > 0, "empty range in randrange({start}, {stop})");
        (i128::from(start) + self.randbelow_u128(width as u128) as i128) as i64
    }

    /// `Random.randrange(start, stop, step)`: `n = ceil(width / step)` with
    /// Python's floor-division spelling for each sign of `step`, then
    /// `start + step * _randbelow(n)`.
    ///
    /// # Panics
    /// If `step == 0` or the range is empty (Python: `ValueError`).
    pub fn randrange_step(&mut self, start: i64, stop: i64, step: i64) -> i64 {
        if step == 1 {
            return self.randrange2(start, stop);
        }
        let width = i128::from(stop) - i128::from(start);
        let istep = i128::from(step);
        let n = if istep > 0 {
            py_floordiv(width + istep - 1, istep)
        } else if istep < 0 {
            py_floordiv(width + istep + 1, istep)
        } else {
            panic!("zero step for randrange()");
        };
        assert!(n > 0, "empty range in randrange({start}, {stop}, {step})");
        (i128::from(start) + istep * self.randbelow_u128(n as u128) as i128) as i64
    }

    /// `Random.randint(a, b)`: `randrange(a, b + 1)`.
    pub fn randint(&mut self, a: i64, b: i64) -> i64 {
        self.randrange2(a, b + 1)
    }

    // -----------------------------------------------------------------------
    // Sequence helpers (Lib/random.py)
    // -----------------------------------------------------------------------

    /// `Random.choice(seq)`: `seq[_randbelow(len(seq))]`.
    ///
    /// # Panics
    /// On an empty slice (Python: `IndexError`).
    pub fn choice<'a, T>(&mut self, seq: &'a [T]) -> &'a T {
        &seq[self.choice_index(seq.len())]
    }

    /// The index `choice` would pick from a sequence of `len` items:
    /// `_randbelow(len)`.
    pub fn choice_index(&mut self, len: usize) -> usize {
        assert!(len > 0, "Cannot choose from an empty sequence");
        self.randbelow(len as u64) as usize
    }

    /// `Random.shuffle(x)`: Fisher-Yates from the end,
    /// `for i in reversed(range(1, len(x))): j = _randbelow(i + 1); swap`.
    pub fn shuffle<T>(&mut self, x: &mut [T]) {
        for i in (1..x.len()).rev() {
            let j = self.randbelow(i as u64 + 1) as usize;
            x.swap(i, j);
        }
    }

    /// `Random.sample(population, k)` (no `counts`): indices into
    /// `population`, CPython 3.12's two-branch algorithm. `setsize = 21`, plus
    /// `4 ** ceil(log(k * 3, 4))` when `k > 5`; if `n <= setsize` draw from a
    /// shrinking pool (`pool[j] = pool[n - i - 1]`), else reject repeats with
    /// a set. The indices returned are the positions drawn, in draw order.
    ///
    /// # Panics
    /// If `k > n` (Python: `ValueError("Sample larger than population or is
    /// negative")`).
    pub fn sample_indices(&mut self, n: usize, k: usize) -> Vec<usize> {
        assert!(k <= n, "Sample larger than population or is negative");
        let mut result = Vec::with_capacity(k);
        let mut setsize: f64 = 21.0;
        if k > 5 {
            // `4 ** _ceil(_log(k * 3, 4))`; math.log(x, 4) is log(x)/log(4).
            let e = ((k * 3) as f64).ln() / 4f64.ln();
            setsize += 4f64.powi(e.ceil() as i32);
        }
        if (n as f64) <= setsize {
            let mut pool: Vec<usize> = (0..n).collect();
            for i in 0..k {
                let j = self.randbelow((n - i) as u64) as usize;
                result.push(pool[j]);
                pool[j] = pool[n - i - 1];
            }
        } else {
            let mut selected: HashSet<usize> = HashSet::with_capacity(k);
            for _ in 0..k {
                let mut j = self.randbelow(n as u64) as usize;
                while selected.contains(&j) {
                    j = self.randbelow(n as u64) as usize;
                }
                selected.insert(j);
                result.push(j);
            }
        }
        result
    }

    /// `Random.sample(population, k)` returning clones of the drawn items.
    pub fn sample<T: Clone>(&mut self, population: &[T], k: usize) -> Vec<T> {
        self.sample_indices(population.len(), k)
            .into_iter()
            .map(|i| population[i].clone())
            .collect()
    }

    /// `Random.choices(population, k=k)` without weights:
    /// `floor(random() * n)` per pick (`n` as a float). Returns indices.
    ///
    /// # Panics
    /// If `n == 0` and `k > 0` (Python: `IndexError`).
    pub fn choices_indices_unweighted(&mut self, n: usize, k: usize) -> Vec<usize> {
        assert!(n > 0 || k == 0, "Cannot choose from an empty population");
        let nf = n as f64;
        (0..k)
            .map(|_| (self.random() * nf).floor() as usize)
            .collect()
    }

    /// `Random.choices(population, weights, k=k)`: `cum_weights =
    /// list(accumulate(weights))` summed left to right, then
    /// [`choices_indices_cum`](Self::choices_indices_cum).
    pub fn choices_indices_weighted(&mut self, weights: &[f64], k: usize) -> Vec<usize> {
        let mut cum = Vec::with_capacity(weights.len());
        let mut total = 0.0;
        for (i, w) in weights.iter().enumerate() {
            // itertools.accumulate: the first element is taken as-is, later
            // ones are `total + w` (not `0.0 + w`, which would lose a -0.0).
            total = if i == 0 { *w } else { total + *w };
            cum.push(total);
        }
        self.choices_indices_cum(&cum, k)
    }

    /// `Random.choices(population, cum_weights=cum_weights, k=k)`:
    /// `total = cum_weights[-1] + 0.0`, each pick is
    /// `bisect.bisect(cum_weights, random() * total, 0, n - 1)`. Returns
    /// indices into a population of `len(cum_weights)` items.
    ///
    /// # Panics
    /// If `total <= 0` or not finite (Python: `ValueError`), or `cum_weights`
    /// is empty.
    pub fn choices_indices_cum(&mut self, cum_weights: &[f64], k: usize) -> Vec<usize> {
        assert!(!cum_weights.is_empty(), "choices() on an empty population");
        let n = cum_weights.len();
        let total = cum_weights[n - 1] + 0.0;
        assert!(total > 0.0, "Total of weights must be greater than zero");
        assert!(total.is_finite(), "Total of weights must be finite");
        let hi = n - 1;
        (0..k)
            .map(|_| {
                let x = self.random() * total;
                bisect_right(cum_weights, x, 0, hi)
            })
            .collect()
    }

    /// `Random.choices(population, weights=None, *, cum_weights=None, k=1)`
    /// returning clones. At most one of `weights` / `cum_weights` may be
    /// given (Python: `TypeError` otherwise); neither means uniform picks.
    ///
    /// # Panics
    /// If both weight forms are given, or a weight list's length differs
    /// from the population's (Python: `TypeError` / `ValueError`).
    pub fn choices<T: Clone>(
        &mut self,
        population: &[T],
        weights: Option<&[f64]>,
        cum_weights: Option<&[f64]>,
        k: usize,
    ) -> Vec<T> {
        let idx = match (weights, cum_weights) {
            (None, None) => self.choices_indices_unweighted(population.len(), k),
            (Some(w), None) => {
                assert!(
                    w.len() == population.len(),
                    "The number of weights does not match the population"
                );
                self.choices_indices_weighted(w, k)
            }
            (None, Some(c)) => {
                assert!(
                    c.len() == population.len(),
                    "The number of weights does not match the population"
                );
                self.choices_indices_cum(c, k)
            }
            (Some(_), Some(_)) => {
                panic!("Cannot specify both weights and cumulative weights")
            }
        };
        idx.into_iter().map(|i| population[i].clone()).collect()
    }

    // -----------------------------------------------------------------------
    // Real-valued distributions (Lib/random.py)
    // -----------------------------------------------------------------------

    /// `Random.uniform(a, b)`: `a + (b - a) * random()`.
    pub fn uniform(&mut self, a: f64, b: f64) -> f64 {
        a + (b - a) * self.random()
    }

    /// `Random.triangular(low, high, mode)`, the three-argument form.
    pub fn triangular(&mut self, low: f64, high: f64, mode: f64) -> f64 {
        let u = self.random();
        if high == low {
            return low;
        }
        let c = (mode - low) / (high - low);
        let (u, c, low, high) = if u > c {
            (1.0 - u, 1.0 - c, high, low)
        } else {
            (u, c, low, high)
        };
        low + (high - low) * (u * c).sqrt()
    }

    /// `Random.expovariate(lambd)`: `-log(1.0 - random()) / lambd`.
    pub fn expovariate(&mut self, lambd: f64) -> f64 {
        -(1.0 - self.random()).ln() / lambd
    }

    /// `Random.gauss(mu, sigma)`: Box-Muller with the spare deviate kept in
    /// `gauss_next` for the next call (so two calls cost two `random()`s).
    pub fn gauss(&mut self, mu: f64, sigma: f64) -> f64 {
        let z = match self.gauss_next.take() {
            Some(z) => z,
            None => {
                let x2pi = self.random() * (2.0 * std::f64::consts::PI);
                let g2rad = (-2.0 * (1.0 - self.random()).ln()).sqrt();
                let z = x2pi.cos() * g2rad;
                self.gauss_next = Some(x2pi.sin() * g2rad);
                z
            }
        };
        mu + z * sigma
    }

    /// `Random.normalvariate(mu, sigma)`: Kinderman-Monahan ratio method.
    pub fn normalvariate(&mut self, mu: f64, sigma: f64) -> f64 {
        let magic = nv_magicconst();
        loop {
            let u1 = self.random();
            let u2 = 1.0 - self.random();
            let z = magic * (u1 - 0.5) / u2;
            let zz = z * z / 4.0;
            if zz <= -u2.ln() {
                return mu + z * sigma;
            }
        }
    }

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    /// `Random.getstate()`: `(VERSION, random_getstate(), gauss_next)`.
    pub fn getstate(&self) -> PyRandomState {
        PyRandomState {
            mt: self.mt,
            index: self.index,
            gauss_next: self.gauss_next.map(f64::to_bits),
        }
    }

    /// `Random.setstate(state)`: restores the 624 words, the index and
    /// `gauss_next`.
    ///
    /// # Panics
    /// If `index > 624` (`random_setstate`: `ValueError("invalid state")`).
    pub fn setstate(&mut self, state: &PyRandomState) {
        assert!(state.index <= N, "invalid state");
        self.mt = state.mt;
        self.index = state.index;
        self.gauss_next = state.gauss_next.map(f64::from_bits);
    }

    /// Build a generator directly from a saved state.
    pub fn from_state(state: &PyRandomState) -> Self {
        let mut r = PyRandom {
            mt: [0; N],
            index: N,
            gauss_next: None,
        };
        r.setstate(state);
        r
    }
}

/// Python's `//` on integers: floor division (rounds toward negative
/// infinity), unlike Rust's `/` (toward zero).
fn py_floordiv(a: i128, b: i128) -> i128 {
    let q = a / b;
    if (a % b != 0) && ((a < 0) != (b < 0)) {
        q - 1
    } else {
        q
    }
}

/// `bisect.bisect_right(a, x, lo, hi)`: insertion point after any entries
/// equal to `x`, searching `a[lo:hi]`.
fn bisect_right(a: &[f64], x: f64, lo: usize, hi: usize) -> usize {
    let (mut lo, mut hi) = (lo, hi);
    while lo < hi {
        let mid = (lo + hi) / 2;
        if x < a[mid] {
            hi = mid;
        } else {
            lo = mid + 1;
        }
    }
    lo
}
