//! Holds `PyRandom` to CPython 3.12's own output.
//!
//! `../../tests/pyrandom_fixtures.json` is generated by
//! `../../tests/gen_pyrandom_fixtures.py` (run it with the repo venv's
//! Python 3.12). Every block there came from a FRESH `random.Random(seed)`,
//! so each assertion below rebuilds the generator the same way. Floats are
//! compared by their IEEE-754 bits.

use super::*;
use serde::Deserialize;

const FIXTURES: &str = include_str!("../../tests/pyrandom_fixtures.json");

#[derive(Deserialize)]
struct Floats {
    bits: Vec<u64>,
    repr: Vec<String>,
}

#[derive(Deserialize)]
struct MixedBits {
    k: Vec<u64>,
    values: Vec<String>,
}

#[derive(Deserialize)]
struct StateRoundtrip {
    first3: Floats,
    after5: Floats,
    index: usize,
    mt_head: Vec<u32>,
    mt_tail: Vec<u32>,
}

#[derive(Deserialize)]
struct GaussState {
    g1: u64,
    g2: u64,
    gauss_next_bits: Option<u64>,
}

#[derive(Deserialize)]
struct InitialState {
    index: usize,
    mt: Vec<u32>,
}

#[derive(Deserialize)]
struct SeedBlock {
    kind: String,
    seed: String,
    random: Floats,
    getrandbits32: Vec<u32>,
    getrandbits_mixed: MixedBits,
    randrange100: Vec<i64>,
    randint16: Vec<i64>,
    randrange_step: Vec<i64>,
    randrange_negstep: Vec<i64>,
    randrange_big: Vec<String>,
    randbelow_huge: Vec<String>,
    uniform: Floats,
    choice7: Vec<usize>,
    choices_weighted: Vec<usize>,
    choices_unweighted: Vec<usize>,
    choices_cum: Vec<usize>,
    choices_intweights: Vec<String>,
    sample_pool: Vec<usize>,
    sample_set: Vec<usize>,
    sample_pool_k6: Vec<usize>,
    sample_set_k6: Vec<usize>,
    expovariate: Floats,
    gauss: Floats,
    normalvariate: Floats,
    triangular: Floats,
    shuffle12: Vec<usize>,
    state_roundtrip: StateRoundtrip,
    gauss_state: GaussState,
    initial_state: InitialState,
}

#[derive(Deserialize)]
struct StrSeedWords {
    s: String,
    words: Vec<u32>,
}

#[derive(Deserialize)]
struct Sha256Block {
    key: String,
    seed: String,
    random: Floats,
}

#[derive(Deserialize)]
struct Fixtures {
    python: String,
    seeds: Vec<SeedBlock>,
    str_seed_words: Vec<StrSeedWords>,
    sha256_prefix16: Vec<Sha256Block>,
}

fn fixtures() -> Fixtures {
    serde_json::from_str(FIXTURES).expect("pyrandom_fixtures.json parses")
}

/// Build the generator the way `random.Random(seed)` was built in Python.
fn rng_for(block: &SeedBlock) -> PyRandom {
    match block.kind.as_str() {
        "int" => {
            let seed: i128 = block.seed.parse().expect("int seed fits i128");
            PyRandom::new_from_i128(seed)
        }
        "str" => PyRandom::new_from_str(&block.seed),
        other => panic!("unknown seed kind {other}"),
    }
}

fn assert_floats(got: &[f64], want: &Floats, what: &str, seed: &str) {
    assert_eq!(
        got.len(),
        want.bits.len(),
        "{what} length for seed {seed:?}"
    );
    for (i, (g, w)) in got.iter().zip(want.bits.iter()).enumerate() {
        assert_eq!(
            g.to_bits(),
            *w,
            "{what}[{i}] for seed {seed:?}: got {g:?} ({:#x}), python {} ({w:#x})",
            g.to_bits(),
            want.repr[i]
        );
    }
}

fn draw<F: FnMut(&mut PyRandom) -> f64>(r: &mut PyRandom, n: usize, mut f: F) -> Vec<f64> {
    (0..n).map(|_| f(r)).collect()
}

fn ordered_float_bits(bits: u64) -> u64 {
    if bits & (1 << 63) == 0 {
        bits | (1 << 63)
    } else {
        !bits
    }
}

fn assert_gaussian_bits_close(got: u64, want: u64, context: &str) {
    // Box-Muller's platform libm sin/cos may round one bit differently.  Keep
    // this tolerance Gaussian-only; random() and every algebraic fixture are
    // required to remain bit-exact with CPython.
    let ulps = ordered_float_bits(got).abs_diff(ordered_float_bits(want));
    assert!(
        ulps <= 1,
        "{context}: got {got:#x}, expected {want:#x} (difference: {ulps} ULPs)"
    );
}

fn assert_gaussian_floats(got: &[f64], want: &Floats, seed: &str) {
    assert_eq!(got.len(), want.bits.len(), "gauss length for seed {seed:?}");
    for (i, (got, want)) in got.iter().zip(&want.bits).enumerate() {
        assert_gaussian_bits_close(
            got.to_bits(),
            *want,
            &format!("gauss[{i}] for seed {seed:?}"),
        );
    }
}

#[test]
fn gaussian_fixture_comparison_allows_one_ulp_of_platform_math_rounding() {
    let python_bits = 0x3ff7_30ed_e0eb_242a;
    let apple_silicon_bits = python_bits + 1;
    assert_gaussian_bits_close(apple_silicon_bits, python_bits, "portable Gaussian fixture");
}

#[test]
#[should_panic(expected = "difference: 2 ULPs")]
fn gaussian_fixture_comparison_rejects_two_ulps() {
    let python_bits = 0x3ff7_30ed_e0eb_242a;
    assert_gaussian_bits_close(python_bits + 2, python_bits, "nonportable Gaussian fixture");
}

#[test]
fn fixtures_come_from_python_3_12() {
    assert!(
        fixtures().python.starts_with("3.12"),
        "{}",
        fixtures().python
    );
}

#[test]
fn initial_state_matches_cpython_seeding() {
    for b in &fixtures().seeds {
        let r = rng_for(b);
        let st = r.getstate();
        assert_eq!(
            st.index, b.initial_state.index,
            "index for seed {:?}",
            b.seed
        );
        assert_eq!(st.mt.len(), b.initial_state.mt.len());
        assert!(
            st.mt[..] == b.initial_state.mt[..],
            "mt words differ for seed {:?}",
            b.seed
        );
        assert_eq!(st.gauss_next, None);
    }
}

#[test]
fn random_matches() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got = draw(&mut r, 20, |r| r.random());
        assert_floats(&got, &b.random, "random", &b.seed);
    }
}

#[test]
fn getrandbits_matches() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got: Vec<u32> = (0..5).map(|_| r.getrandbits(32) as u32).collect();
        assert_eq!(
            got, b.getrandbits32,
            "getrandbits(32) for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        for (k, want) in b
            .getrandbits_mixed
            .k
            .iter()
            .zip(b.getrandbits_mixed.values.iter())
        {
            let got = r.getrandbits(*k as u32);
            assert_eq!(
                got.to_string(),
                *want,
                "getrandbits({k}) for seed {:?}",
                b.seed
            );
        }
        // The word form agrees with the integer form.
        let mut a = rng_for(b);
        let mut c = rng_for(b);
        for k in [1u64, 31, 32, 33, 64, 65, 100, 128] {
            let words = a.getrandbits_words(k);
            let int = c.getrandbits(k as u32);
            let mut v: u128 = 0;
            for (i, w) in words.iter().enumerate() {
                v |= u128::from(*w) << (32 * i);
            }
            assert_eq!(v, int, "getrandbits_words({k}) for seed {:?}", b.seed);
        }
    }
}

#[test]
fn getrandbits_zero_draws_nothing() {
    let mut a = PyRandom::new_from_i64(42);
    let mut c = PyRandom::new_from_i64(42);
    assert_eq!(a.getrandbits(0), 0);
    assert_eq!(a.random(), c.random());
}

#[test]
fn randrange_and_randint_match() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got: Vec<i64> = (0..10).map(|_| r.randrange(100)).collect();
        assert_eq!(got, b.randrange100, "randrange(100) for seed {:?}", b.seed);

        let mut r = rng_for(b);
        let got: Vec<i64> = (0..10).map(|_| r.randint(1, 6)).collect();
        assert_eq!(got, b.randint16, "randint(1, 6) for seed {:?}", b.seed);

        let mut r = rng_for(b);
        let got: Vec<i64> = (0..10).map(|_| r.randrange_step(-50, 50, 7)).collect();
        assert_eq!(
            got, b.randrange_step,
            "randrange(-50, 50, 7) for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        let got: Vec<i64> = (0..10).map(|_| r.randrange_step(50, -50, -3)).collect();
        assert_eq!(
            got, b.randrange_negstep,
            "randrange(50, -50, -3) for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        let got: Vec<String> = (0..6)
            .map(|_| r.randrange((1i64 << 40) + 3).to_string())
            .collect();
        assert_eq!(
            got, b.randrange_big,
            "randrange(2**40 + 3) for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        let got: Vec<String> = (0..4)
            .map(|_| r.randbelow_u128((1u128 << 70) + 5).to_string())
            .collect();
        assert_eq!(
            got, b.randbelow_huge,
            "_randbelow(2**70 + 5) for seed {:?}",
            b.seed
        );
    }
}

#[test]
fn uniform_matches() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got = draw(&mut r, 10, |r| r.uniform(-3.5, 10.25));
        assert_floats(&got, &b.uniform, "uniform", &b.seed);
    }
}

#[test]
fn choice_matches() {
    let pop: Vec<usize> = (0..7).collect();
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got: Vec<usize> = (0..10).map(|_| *r.choice(&pop)).collect();
        assert_eq!(got, b.choice7, "choice(range(7)) for seed {:?}", b.seed);
    }
}

#[test]
fn choices_match() {
    let weights = [0.1, 0.4, 0.2, 0.25, 0.05];
    let pop5: Vec<usize> = (0..5).collect();
    let pop4: Vec<usize> = (0..4).collect();
    let abc = ["a".to_string(), "b".to_string(), "c".to_string()];
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got = r.choices(&pop5, Some(&weights), None, 10);
        assert_eq!(
            got, b.choices_weighted,
            "choices(weights=...) for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        let got = r.choices(&pop5, None, None, 10);
        assert_eq!(
            got, b.choices_unweighted,
            "choices() unweighted for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        let got = r.choices(&pop4, None, Some(&[1.0, 3.0, 3.0, 10.0]), 10);
        assert_eq!(
            got, b.choices_cum,
            "choices(cum_weights=...) for seed {:?}",
            b.seed
        );

        let mut r = rng_for(b);
        let got = r.choices(&abc, Some(&[5.0, 1.0, 4.0]), None, 10);
        assert_eq!(
            got, b.choices_intweights,
            "choices(int weights) for seed {:?}",
            b.seed
        );
    }
}

#[test]
fn sample_matches_both_branches() {
    for b in &fixtures().seeds {
        // n=50, k=8: setsize = 21 + 4**ceil(log4(24)) = 21 + 64 -> pool branch.
        let mut r = rng_for(b);
        assert_eq!(
            r.sample_indices(50, 8),
            b.sample_pool,
            "sample(range(50), 8) for seed {:?}",
            b.seed
        );
        // n=500, k=3: setsize = 21 -> set branch.
        let mut r = rng_for(b);
        assert_eq!(
            r.sample_indices(500, 3),
            b.sample_set,
            "sample(range(500), 3) for seed {:?}",
            b.seed
        );
        // k=6: setsize = 21 + 4**ceil(log4(18)) = 21 + 64 = 85.
        let mut r = rng_for(b);
        assert_eq!(
            r.sample_indices(60, 6),
            b.sample_pool_k6,
            "sample(range(60), 6) for seed {:?}",
            b.seed
        );
        let mut r = rng_for(b);
        assert_eq!(
            r.sample_indices(100, 6),
            b.sample_set_k6,
            "sample(range(100), 6) for seed {:?}",
            b.seed
        );
        // The cloning form agrees with the index form.
        let pop: Vec<u32> = (0..50).map(|i| i * 10).collect();
        let mut r = rng_for(b);
        let got = r.sample(&pop, 8);
        let want: Vec<u32> = b.sample_pool.iter().map(|i| pop[*i]).collect();
        assert_eq!(got, want);
    }
}

#[test]
fn real_distributions_match() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let got = draw(&mut r, 5, |r| r.expovariate(1.0 / 45.0));
        assert_floats(&got, &b.expovariate, "expovariate", &b.seed);

        let mut r = rng_for(b);
        let got = draw(&mut r, 6, |r| r.gauss(0.0, 1.0));
        assert_gaussian_floats(&got, &b.gauss, &b.seed);

        let mut r = rng_for(b);
        let got = draw(&mut r, 6, |r| r.normalvariate(2.0, 3.0));
        assert_floats(&got, &b.normalvariate, "normalvariate", &b.seed);

        let mut r = rng_for(b);
        let got = draw(&mut r, 4, |r| r.triangular(1.0, 9.0, 3.0));
        assert_floats(&got, &b.triangular, "triangular", &b.seed);
    }
}

#[test]
fn shuffle_matches() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let mut v: Vec<usize> = (0..12).collect();
        r.shuffle(&mut v);
        assert_eq!(v, b.shuffle12, "shuffle(range(12)) for seed {:?}", b.seed);
    }
}

#[test]
fn getstate_setstate_roundtrip() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let first3 = draw(&mut r, 3, |r| r.random());
        assert_floats(&first3, &b.state_roundtrip.first3, "first3", &b.seed);
        let st = r.getstate();
        assert_eq!(
            st.index, b.state_roundtrip.index,
            "index for seed {:?}",
            b.seed
        );
        assert_eq!(&st.mt[..4], &b.state_roundtrip.mt_head[..]);
        assert_eq!(&st.mt[620..624], &b.state_roundtrip.mt_tail[..]);
        let after5 = draw(&mut r, 5, |r| r.random());
        assert_floats(&after5, &b.state_roundtrip.after5, "after5", &b.seed);
        r.setstate(&st);
        let restored5 = draw(&mut r, 5, |r| r.random());
        assert_floats(&restored5, &b.state_roundtrip.after5, "restored5", &b.seed);
        // A clone and from_state() are the same thing.
        let mut cloned = PyRandom::from_state(&st);
        let again = draw(&mut cloned, 5, |r| r.random());
        assert_floats(&again, &b.state_roundtrip.after5, "from_state", &b.seed);
        let c2 = cloned.clone();
        assert_eq!(c2, cloned);
    }
}

#[test]
fn gauss_next_survives_state() {
    for b in &fixtures().seeds {
        let mut r = rng_for(b);
        let g1 = r.gauss(0.0, 1.0);
        assert_gaussian_bits_close(
            g1.to_bits(),
            b.gauss_state.g1,
            &format!("gauss #1 for seed {:?}", b.seed),
        );
        let st = r.getstate();
        assert_gaussian_bits_close(
            st.gauss_next.expect("gauss caches the second draw"),
            b.gauss_state
                .gauss_next_bits
                .expect("fixture contains the cached second draw"),
            &format!("gauss_next in state for seed {:?}", b.seed),
        );
        let g2 = r.gauss(0.0, 1.0);
        assert_gaussian_bits_close(
            g2.to_bits(),
            b.gauss_state.g2,
            &format!("gauss #2 for seed {:?}", b.seed),
        );
        r.setstate(&st);
        assert_eq!(r.gauss(0.0, 1.0).to_bits(), g2.to_bits());
    }
}

#[test]
fn str_seed_words_match_sha512_path() {
    for w in &fixtures().str_seed_words {
        assert_eq!(seed_from_str_to_words(&w.s), w.words, "words for {:?}", w.s);
    }
}

#[test]
fn sha256_prefix16_seeding_matches_traffic_manager() {
    for b in &fixtures().sha256_prefix16 {
        let seed: u64 = b.seed.parse().unwrap();
        assert_eq!(sha256_prefix16(&b.key), seed, "seed for {:?}", b.key);
        let mut r = PyRandom::new_from_sha256_prefix16(&b.key);
        let got = draw(&mut r, 5, |r| r.random());
        assert_floats(&got, &b.random, "sha256 random", &b.key);
    }
}

#[test]
fn int_seeding_paths_agree() {
    // Every int constructor is the same key once the magnitude is split.
    let a = PyRandom::new_from_i64(-5);
    let b = PyRandom::new_from_u64(5);
    let c = PyRandom::new_from_i128(5);
    let d = PyRandom::new_from_int_words(&[5, 0, 0]);
    let e = PyRandom::new_from_big_uint_le(&[5, 0, 0, 0, 0, 0, 0, 0, 0]);
    let f = init_by_array(&[5]);
    assert_eq!(a, b);
    assert_eq!(b, c);
    assert_eq!(c, d);
    assert_eq!(d, e);
    assert_eq!(e, f);
    // 2**32 is the two-word key [0, 1], not [1].
    let big = PyRandom::new_from_u64(1 << 32);
    assert_eq!(big, init_by_array(&[0, 1]));
    assert_ne!(big, init_by_array(&[1]));
    // Zero is the one-word key [0].
    assert_eq!(PyRandom::new_from_i64(0), init_by_array(&[0]));
    assert_eq!(int_words_from_le_bytes(&[]), vec![0]);
}

#[test]
fn seed_methods_reset_like_constructors() {
    let mut r = PyRandom::new_from_i64(1);
    let _ = r.random();
    r.seed_i64(7);
    assert_eq!(r, PyRandom::new_from_i64(7));
    r.seed_str("parking:0:12");
    assert_eq!(r, PyRandom::new_from_str("parking:0:12"));
}

#[test]
fn unseeded_generators_differ() {
    let mut a = PyRandom::new_unseeded();
    let mut b = PyRandom::new_unseeded();
    let sa: Vec<f64> = draw(&mut a, 4, |r| r.random());
    let sb: Vec<f64> = draw(&mut b, 4, |r| r.random());
    assert_ne!(sa, sb);
}

#[test]
fn floordiv_is_pythons() {
    assert_eq!(py_floordiv(7, 2), 3);
    assert_eq!(py_floordiv(-7, 2), -4);
    assert_eq!(py_floordiv(7, -2), -4);
    assert_eq!(py_floordiv(-7, -2), 3);
    assert_eq!(py_floordiv(6, -3), -2);
}

#[test]
fn bisect_right_is_pythons() {
    let a = [1.0, 3.0, 3.0, 10.0];
    assert_eq!(bisect_right(&a, 0.5, 0, 3), 0);
    assert_eq!(bisect_right(&a, 1.0, 0, 3), 1);
    assert_eq!(bisect_right(&a, 3.0, 0, 3), 3);
    assert_eq!(bisect_right(&a, 9.99, 0, 3), 3);
    assert_eq!(bisect_right(&a, 10.0, 0, 3), 3);
}
