"""Bake the loose runtime data files into an importable Python module.

The release build (``tools/build_release.py``) runs this before Nuitka --
alongside ``bake_world.py`` -- so the runtime data files under
``freight_fate/data`` (buffs, city services, facility approaches, the
radio catalog, the curve shard, ...) ship compiled into the executable
instead of as editable JSON next to it. Source checkouts never carry the
baked module: ``data_resources.read_data_text`` falls back to reading
the files directly, so the data stays editable there.

The file list lives in ``freight_fate.data.data_resources.BAKED_DATA_FILES``
next to the reader; register new runtime data files there.

Run from the repository root: ``uv run python tools/bake_data.py``
"""

from __future__ import annotations

import argparse
import base64
import importlib.util
import json
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "src"
DATA_DIR = SRC_DIR / "freight_fate" / "data"
DEFAULT_OUTPUT = DATA_DIR / "_baked_data.py"
_CHUNK = 96

_HEADER = '''\
"""Baked runtime data files for frozen builds.

Generated by tools/bake_data.py; never edit or commit. Release builds
compile this module into the executable so packaged builds ship no
editable data files; source checkouts read the files directly instead.
"""

import base64
import json
import zlib

_PAYLOAD_B85 = (
'''

_FOOTER = '''\
)


def load() -> dict:
    """Return {relative path: file text} for every baked data file."""
    return json.loads(zlib.decompress(base64.b85decode(_PAYLOAD_B85)))
'''


def _baked_file_list() -> tuple[str, ...]:
    """Import the registration list by path (works without an installed package)."""
    spec = importlib.util.spec_from_file_location(
        "data_resources", DATA_DIR / "data_resources.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.BAKED_DATA_FILES


def bake(output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the baked data module and return its path."""
    payload = {}
    for relative in _baked_file_list():
        path = DATA_DIR / Path(relative)
        if not path.exists():
            raise FileNotFoundError(f"registered runtime data file is missing: {path}")
        payload[relative] = path.read_text(encoding="utf-8")
    raw = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    encoded = base64.b85encode(zlib.compress(raw, 9)).decode("ascii")
    chunks = "".join(f'    "{encoded[i : i + _CHUNK]}"\n' for i in range(0, len(encoded), _CHUNK))
    output.write_text(_HEADER + chunks + _FOOTER, encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="where to write the baked module (default: the game's data package)",
    )
    args = parser.parse_args()
    out = bake(output=args.out)
    print(f"Baked runtime data into {out} ({out.stat().st_size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
