"""Bake the radio station catalog into an importable Python module.

The release build (``tools/build_release.py``) runs this before Nuitka so the
catalog ships compiled into the executable instead of as an editable JSON file
next to it -- the same arrangement as ``tools/bake_world.py`` and for the same
reason. Source checkouts never carry the baked module: the game falls back to
reading ``data/radio/stations.json`` directly, so the catalog stays editable
there. The output is deterministic for identical input.

Run from the repository root: ``uv run python tools/bake_radio.py``
"""

from __future__ import annotations

import argparse
import base64
import json
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "src"
CATALOG_PATH = SRC_DIR / "freight_fate" / "data" / "radio" / "stations.json"
DEFAULT_OUTPUT = SRC_DIR / "freight_fate" / "data" / "_baked_radio.py"
_CHUNK = 96

_HEADER = '''\
"""Baked radio catalog for frozen builds.

Generated by tools/bake_radio.py; never edit or commit. Release builds compile
this module into the executable so packaged builds ship no editable data
files; source checkouts read data/radio/stations.json instead.
"""

import base64
import json
import zlib

_PAYLOAD_B85 = (
'''

_FOOTER = '''\
)


def load() -> dict:
    """Return the catalog exactly as ``load_catalog`` reads it from JSON."""
    return json.loads(zlib.decompress(base64.b85decode(_PAYLOAD_B85)))
'''


def bake(catalog_path: Path = CATALOG_PATH, output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the baked catalog module and return its path."""
    data = json.loads(catalog_path.read_text(encoding="utf-8"))
    raw = json.dumps(data, separators=(",", ":"), sort_keys=True).encode("utf-8")
    encoded = base64.b85encode(zlib.compress(raw, 9)).decode("ascii")
    chunks = "".join(f'    "{encoded[i : i + _CHUNK]}"\n' for i in range(0, len(encoded), _CHUNK))
    output.write_text(_HEADER + chunks + _FOOTER, encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="where to write the baked module (default: the game's data package)",
    )
    args = parser.parse_args()
    out = bake(output=args.out)
    print(f"Baked radio catalog into {out} ({out.stat().st_size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
