"""Bake the indexed world data into an importable Python module.

The release build (``tools/build_release.py``) runs this before Nuitka so
the world ships compiled into the executable instead of as editable JSON
files next to it. Source checkouts never carry the baked module: the game
falls back to reading ``world_data/`` directly, so the data stays editable
there. The output is deterministic for identical world data.

Run from the repository root: ``uv run python tools/bake_world.py``
"""

from __future__ import annotations

import argparse
import base64
import importlib.util
import json
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "src"
WORLD_DATA_PATH = SRC_DIR / "freight_fate" / "data" / "world_data"
DEFAULT_OUTPUT = SRC_DIR / "freight_fate" / "data" / "_baked_world.py"
_CHUNK = 96

_HEADER = '''\
"""Baked world data for frozen builds.

Generated by tools/bake_world.py; never edit or commit. Release builds
compile this module into the executable so packaged builds ship no
editable world files; source checkouts read world_data/ instead.
"""

import base64
import json
import zlib

_PAYLOAD_B85 = (
'''

_FOOTER = '''\
)


def load() -> dict:
    """Return the merged world data exactly as ``load_world_data`` reads it."""
    return json.loads(zlib.decompress(base64.b85decode(_PAYLOAD_B85)))
'''


def _load_world_loader():
    """Import the game's world loader by path (works without an installed package)."""
    spec = importlib.util.spec_from_file_location(
        "world_loader", SRC_DIR / "freight_fate" / "data" / "world_loader.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def bake(world_data_root: Path = WORLD_DATA_PATH, output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the baked world module and return its path."""
    data = _load_world_loader().load_world_data(world_data_root)
    raw = json.dumps(data, separators=(",", ":"), sort_keys=True).encode("utf-8")
    encoded = base64.b85encode(zlib.compress(raw, 9)).decode("ascii")
    chunks = "".join(f'    "{encoded[i : i + _CHUNK]}"\n' for i in range(0, len(encoded), _CHUNK))
    output.write_text(_HEADER + chunks + _FOOTER, encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="where to write the baked module (default: the game's data package)",
    )
    args = parser.parse_args()
    out = bake(output=args.out)
    print(f"Baked world data into {out} ({out.stat().st_size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
